server:
  port: 8098

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jgarea/springbootmicroservicios-config.git
          force-pull: true
          clone-on-start: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8099/eureka/}